services:
  app:
    build: .
    container_name: ${CONTAINER_NAME:-STREAMER1}
    env_file:
      - .env
    restart: unless-stopped
    shm_size: '256m'
    mem_limit: 1536m
    memswap_limit: 1536m
    volumes:
      - ./config.yml:/app/config.yml:ro
    privileged: true
    environment:
      - TZ=${TZ:-Europe/London}   # change as needed
      - SMB_PATH=${SMB_PATH}
      - SMB_USERNAME=${SMB_USERNAME}
      - SMB_PASSWORD=${SMB_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
